# Generated by Django 5.0.13 on 2025-12-04 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agente_Inmobiliario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('licencia_agente', models.CharField(max_length=50)),
                ('fecha_contratacion', models.DateField()),
                ('salario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('comision_porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente_Inmobiliaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('preferencias_propiedad', models.TextField(blank=True, null=True)),
                ('presupuesto_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('dni', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('direccion_propietario', models.CharField(max_length=255)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('dni', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=255)),
                ('tipo_propiedad', models.CharField(max_length=50)),
                ('num_habitaciones', models.IntegerField()),
                ('num_banos', models.IntegerField()),
                ('superficie_m2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_venta', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('precio_alquiler', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('estado_propiedad', models.CharField(max_length=50)),
                ('fecha_publicacion', models.DateField(auto_now_add=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propiedades', to='inmobiliaria.propietario')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato_Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_contrato', models.DateField()),
                ('precio_final', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fecha_cierre', models.DateField()),
                ('estado_contrato', models.CharField(max_length=50)),
                ('comision_agente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos_venta', to='inmobiliaria.agente_inmobiliario')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos_venta', to='inmobiliaria.cliente_inmobiliaria')),
                ('propiedad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contrato_venta', to='inmobiliaria.propiedad')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos_venta', to='inmobiliaria.propietario')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato_Alquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('monto_alquiler_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_contrato', models.CharField(max_length=50)),
                ('deposito_garantia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos_alquiler', to='inmobiliaria.agente_inmobiliario')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos_alquiler', to='inmobiliaria.cliente_inmobiliaria')),
                ('propiedad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contrato_alquiler', to='inmobiliaria.propiedad')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos_alquiler', to='inmobiliaria.propietario')),
            ],
        ),
        migrations.CreateModel(
            name='Visita_Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_visita', models.DateField()),
                ('hora_visita', models.TimeField()),
                ('comentarios_cliente', models.TextField(blank=True, null=True)),
                ('calificacion_propiedad', models.IntegerField(blank=True, null=True)),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='inmobiliaria.agente_inmobiliario')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='inmobiliaria.cliente_inmobiliaria')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='inmobiliaria.propiedad')),
            ],
        ),
    ]
